In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob

In [2]:
filelist = glob.glob("/win/Users/faust/Documents/TCC_MBA/ABM_Project/Results_temp/Apj_R/*.csv")
len(filelist)

77

In [3]:
df = pd.DataFrame()
for file in filelist:
    df_temp = pd.read_csv(file)
    df = pd.concat([df, df_temp])

In [4]:
df.shape

(2703838, 30)

In [5]:
df.columns

Index(['agente', 'ag_tamanho', 'ag_investimento', 'ag_max_alpha',
       'ag_atratividade', 'factor', 'agente_alpha_ofertado', 'bid',
       'bid_number', 'estado', 'pop_alvo', 'pop_alvo_ratio', 'pj_tamanho',
       'pj_investimento', 'bid_alpha', 'outorga', 'run', 'reruns',
       'par_bid_alpha', 'par_std_alpha', 'par_atrat_avg', 'par_std_dev',
       'par_number_of_agents', 'par_max_alpha', 'par_atrat_lim',
       'par_distribution', 'par_reatividade', 'par_reruns', 'par_runs',
       'file_name'],
      dtype='object')

In [6]:
colunas = sorted(df['par_bid_alpha'].unique().tolist())
colunas.remove(1)
colunas.append(1)
colunas

[0.5, 0.6, 0.7, 0.8, 0.9, 1.1, 1.2, 1.3, 1.4, 1.5, 1]

In [7]:
lista_reat = [0, 0.1, 0.2, 0.3, 0.4]
table_list = []
for n in lista_reat:
    filt = (
         (df['agente'] == 'nobid')
        & (df['par_reatividade'] == n)
    )

    dfx = df.loc[filt]
    line = dfx.pivot_table(index=['par_reatividade', 'run'], values='pop_alvo_ratio',
                          columns='file_name', aggfunc=np.sum).mean().tolist()
    table_list.append(line)

df_final1 = 1 - pd.DataFrame(table_list, columns=colunas, index=lista_reat)
df_final1.reindex(sorted(df_final1.columns), axis=1).round(2)

      0.5   0.6   0.7   0.8   0.9   1.0   1.1   1.2   1.3   1.4   1.5
0.0  0.96  0.94  0.90  0.87  0.82  0.75  0.63  0.46  0.27  0.07  0.00
0.1  0.97  0.96  0.94  0.90  0.86  0.81  0.75  0.63  0.44  0.26  0.07
0.2  0.98  0.97  0.96  0.93  0.90  0.85  0.81  0.75  0.63  0.45  0.26
0.3  0.98  0.98  0.97  0.96  0.93  0.90  0.85  0.81  0.76  0.62  0.45
0.4  0.98  0.98  0.98  0.97  0.96  0.93  0.89  0.86  0.82  0.76  0.63

In [8]:
df_pop = df_final1.reset_index().melt(id_vars='index', var_name='Apj',
                                     value_name='coverage').set_index(['index', 'Apj'])

In [9]:
lista_reat = [0, 0.1, 0.2, 0.3, 0.4]
table_list = []
for reat in lista_reat:
    filt = (
#          (df['agente'] == 'nobid')
        (df['par_reatividade'] == reat)
    )

    dfx = df.loc[filt]
    line = dfx.pivot_table(index=['par_reatividade', 'run'], values='bid',
                          columns='file_name', aggfunc=np.sum).mean().tolist()
    table_list.append(line)

df_final2 = pd.DataFrame(table_list, columns=colunas, index=lista_reat)
df_final2.reindex(sorted(df_final2.columns), axis=1).round(2)

      0.5   0.6   0.7   0.8   0.9   1.0   1.1   1.2   1.3   1.4   1.5
0.0  0.84  0.88  0.90  0.91  0.91  0.86  0.76  0.58  0.35  0.09  0.00
0.1  0.84  0.89  0.92  0.94  0.95  0.93  0.90  0.79  0.58  0.36  0.11
0.2  0.84  0.90  0.94  0.97  0.98  0.98  0.97  0.96  0.85  0.65  0.40
0.3  0.85  0.90  0.95  0.99  1.02  1.03  1.04  1.06  1.07  0.93  0.71
0.4  0.85  0.91  0.96  1.00  1.04  1.07  1.11  1.16  1.21  1.20  1.03

In [10]:
df_bid = df_final2.reset_index().melt(id_vars='index', var_name='Apj', value_name='bid').set_index(['index', 'Apj'])

In [11]:
lista_reat = [0, 0.1, 0.2, 0.3, 0.4]
table_list = []
for reat in lista_reat:
    filt = (
#          (df['agente'] == 'nobid')
        (df['par_reatividade'] == reat)
    )

    dfx = df.loc[filt]
    line = dfx.pivot_table(index=['par_reatividade', 'run'], values='bid',
                          columns='file_name', aggfunc='count').mean().tolist()
    table_list.append(line)
    
df_final3 = pd.DataFrame(table_list, columns=colunas, index=lista_reat)
df_final3.reindex(sorted(df_final3.columns), axis=1).round(1)

      0.5   0.6   0.7   0.8   0.9   1.0   1.1   1.2   1.3   1.4   1.5
0.0  25.0  25.0  25.0  25.0  25.0  25.0  25.0  25.0  25.0  25.0  25.0
0.1  27.4  28.6  29.7  30.9  31.8  33.3  36.4  40.5  44.9  48.7  50.0
0.2  27.6  28.6  29.9  31.0  32.0  33.5  36.6  40.6  44.9  48.7  50.0
0.3  27.5  28.8  30.1  31.3  32.3  33.6  36.8  40.9  45.0  48.8  50.0
0.4  27.4  28.8  30.1  31.3  32.5  33.9  37.1  40.9  45.2  48.8  50.0

In [12]:
df_trys = df_final3.reset_index().melt(id_vars='index', var_name='Apj', 
                                      value_name='trys').set_index(['index', 'Apj'])

In [13]:
df_table = pd.concat([df_pop, df_bid, df_trys], axis=1)
df_table = df_table.reset_index()
df_table.rename(columns = {'index':'R',}, inplace = True)
df_table

      R  Apj  coverage       bid    trys
0   0.0  0.5  0.961290  0.837102  25.000
1   0.1  0.5  0.971590  0.838162  27.421
2   0.2  0.5  0.981158  0.842460  27.594
3   0.3  0.5  0.982826  0.845024  27.516
4   0.4  0.5  0.978745  0.852406  27.410
5   0.0  0.6  0.937758  0.875917  25.000
6   0.1  0.6  0.959335  0.888104  28.600
7   0.2  0.6  0.973823  0.897129  28.600
8   0.3  0.6  0.981014  0.899885  28.756
9   0.4  0.6  0.983453  0.907539  28.799
10  0.0  0.7  0.904260  0.901446  25.000
11  0.1  0.7  0.935178  0.923352  29.665
12  0.2  0.7  0.957186  0.937590  29.892
13  0.3  0.7  0.972286  0.948879  30.101
14  0.4  0.7  0.980679  0.957178  30.141
15  0.0  0.8  0.865807  0.908987  25.000
16  0.1  0.8  0.900103  0.940521  30.861
17  0.2  0.8  0.932565  0.966855  31.050
18  0.3  0.8  0.957050  0.991777  31.297
19  0.4  0.8  0.972469  1.003289  31.342
20  0.0  0.9  0.821126  0.909039  25.000
21  0.1  0.9  0.861626  0.945768  31.803
22  0.2  0.9  0.898793  0.981593  32.011
23  0.3  0.9  0.934226  1.018320  32.255
24  0.4  0.9  0.958649  1.043292  32.472
25  0.0  1.1  0.632617  0.755945  25.000
26  0.1  1.1  0.753085  0.897060  36.403
27  0.2  1.1  0.808619  0.973956  36.575
28  0.3  1.1  0.853021  1.041902  36.773
29  0.4  1.1  0.894975  1.110594  37.066
30  0.0  1.2  0.462603  0.580397  25.000
31  0.1  1.2  0.627891  0.786149  40.498
32  0.2  1.2  0.751243  0.957868  40.622
33  0.3  1.2  0.809265  1.063117  40.851
34  0.4  1.2  0.856369  1.162704  40.892
35  0.0  1.3  0.265314  0.349100  25.000
36  0.1  1.3  0.442339  0.584871  44.906
37  0.2  1.3  0.626364  0.848611  44.913
38  0.3  1.3  0.758620  1.068350  44.985
39  0.4  1.3  0.815690  1.208409  45.166
40  0.0  1.4  0.067056  0.092576  25.000
41  0.1  1.4  0.257395  0.361188  48.713
42  0.2  1.4  0.451154  0.652410  48.728
43  0.3  1.4  0.621612  0.933338  48.800
44  0.4  1.4  0.760458  1.201389  48.817
45  0.0  1.5  0.000535  0.002522  25.000
46  0.1  1.5  0.072228  0.106916  49.971
47  0.2  1.5  0.264849  0.402738  49.965
48  0.3  1.5  0.452763  0.710617  49.976
49  0.4  1.5  0.629779  1.028244  49.963
50  0.0  1.0  0.753658  0.864828  25.000
51  0.1  1.0  0.811596  0.928652  33.302
52  0.2  1.0  0.853908  0.976554  33.511
53  0.3  1.0  0.897470  1.028519  33.648
54  0.4  1.0  0.931885  1.071755  33.904

In [14]:
df_table.to_excel('/win/Users/faust/Documents/TCC_MBA/ABM_Project/Results_temp/Apj_R/Apj_R_003.xlsx', index=False)